# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad5ccf900db07584efd44743e625abf3f6213322f1f0ef8c421757bdb2d38c248e4f5cc417685f4c080a1838648d6824645f3d389462ed29dc32a51e1808a9e4

test:
  secret_key_base: 3963a0b318f190ce9e37da5cb5787ba944b5ee3d5718cdc6d1deee8a27f35243ccfe90e1844a5979c1b28906ee8e197cbc7ad739158dbc78db8e0d635738bf3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
